// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: ezT75DcpvKbBPxGoHLTCXX
// Component: ItGKFxds3h
import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";

import * as p from "@plasmicapp/react-web";

import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic_blank_project.module.css"; // plasmic-import: ezT75DcpvKbBPxGoHLTCXX/projectcss
import sty from "./PlasmicInside.module.css"; // plasmic-import: ItGKFxds3h/css

export type PlasmicInside__VariantMembers = {};

export type PlasmicInside__VariantsArgs = {};
type VariantPropType = keyof PlasmicInside__VariantsArgs;
export const PlasmicInside__VariantProps = new Array<VariantPropType>();

export type PlasmicInside__ArgsType = {};
type ArgPropType = keyof PlasmicInside__ArgsType;
export const PlasmicInside__ArgProps = new Array<ArgPropType>();

export type PlasmicInside__OverridesType = {
  root?: p.Flex<"div">;
  link?: p.Flex<"a"> & Partial<LinkProps>;
  _?: p.Flex<typeof p.PlasmicImg>;
  ul?: p.Flex<"ul">;
  li?: p.Flex<"li">;
  img?: p.Flex<typeof p.PlasmicImg>;
};

export interface DefaultInsideProps {}

function PlasmicInside__RenderFunc(props: {
  variants: PlasmicInside__VariantsArgs;
  args: PlasmicInside__ArgsType;
  overrides: PlasmicInside__OverridesType;

  forNode?: string;
}) {
  const { variants, args, overrides, forNode } = props;

  return (
    <React.Fragment>
      <Head>
        <meta name="twitter:card" content="summary" />
      </Head>

      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div className={projectcss.plasmic_page_wrapper}>
        <p.Stack
          as={"div"}
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          hasGap={true}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            sty.root
          )}
        >
          <p.PlasmicLink
            data-plasmic-name={"link"}
            data-plasmic-override={overrides.link}
            className={classNames(projectcss.a, sty.link)}
            component={Link}
            href={"/whatareyoudoing" as const}
            platform={"nextjs"}
          >
            <p.PlasmicImg
              data-plasmic-name={"_"}
              data-plasmic-override={overrides._}
              alt={"error.return();" as const}
              className={classNames(sty._)}
              displayHeight={"224px" as const}
              displayMaxHeight={"none" as const}
              displayMaxWidth={"100%" as const}
              displayMinHeight={"0" as const}
              displayMinWidth={"0" as const}
              displayWidth={"auto" as const}
              loading={"lazy" as const}
              src={{
                src: "/plasmic/blank_project/images/logoApng2.png",
                fullWidth: 381,
                fullHeight: 171,
                aspectRatio: undefined
              }}
            />
          </p.PlasmicLink>

          <div
            className={classNames(
              projectcss.all,
              projectcss.__wab_text,
              sty.text__srJ
            )}
          >
            <React.Fragment>
              <React.Fragment>
                {
                  "Hello! Welcome to My Website, JakesMusicFactory.Plasmic.Site\n\nIf you would like a tour, please come to: \n47.41016193420535, -84.01577880247932\n\nAnd give us a contact at:\njakesmusicfact@gmail.com\n\nWe're waiting to show you around!\n\nP.s. sorry if theres any issues with the website, i'm new to this type of thing\n"
                }
              </React.Fragment>
              <ul
                data-plasmic-name={"ul"}
                data-plasmic-override={overrides.ul}
                className={classNames(projectcss.ul, sty.ul)}
              >
                <li
                  data-plasmic-name={"li"}
                  data-plasmic-override={overrides.li}
                  className={classNames(
                    projectcss.li,
                    projectcss.__wab_text,
                    sty.li
                  )}
                >
                  {""}
                </li>
              </ul>
              <React.Fragment>{"\n"}</React.Fragment>
            </React.Fragment>
          </div>

          <div
            className={classNames(
              projectcss.all,
              projectcss.__wab_text,
              sty.text__ha6A
            )}
          >
            {
              "FAQ:\n\nQ: What is this business? \nA: We're a factory that mainly makes music, we make discs, instruments, and music of our own.\n\nQ:  How much is it to visit?\nA: All tours are currently free until the end of the month.\n\nQ: Can i bring food or drink inside?\nA: No, please refrain from bringing food inside.\n\n"
            }
          </div>

          <p.PlasmicImg
            data-plasmic-name={"img"}
            data-plasmic-override={overrides.img}
            alt={""}
            className={classNames(sty.img)}
            displayHeight={"auto" as const}
            displayMaxHeight={"none" as const}
            displayMaxWidth={"100%" as const}
            displayMinHeight={"0" as const}
            displayMinWidth={"0" as const}
            displayWidth={"auto" as const}
            loading={"lazy" as const}
            src={{
              src: "/plasmic/blank_project/images/baldiTalk0001Png.png",
              fullWidth: 226,
              fullHeight: 236,
              aspectRatio: undefined
            }}
          />
        </p.Stack>
      </div>
    </React.Fragment>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root", "link", "_", "ul", "li", "img"],
  link: ["link", "_"],
  _: ["_"],
  ul: ["ul", "li"],
  li: ["li"],
  img: ["img"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  typeof PlasmicDescendants[T][number];
type NodeDefaultElementType = {
  root: "div";
  link: "a";
  _: typeof p.PlasmicImg;
  ul: "ul";
  li: "li";
  img: typeof p.PlasmicImg;
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicInside__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicInside__VariantsArgs;
    args?: PlasmicInside__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicInside__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    // Specify args directly as props
    Omit<PlasmicInside__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicInside__ArgProps,
      internalVariantPropNames: PlasmicInside__VariantProps
    });

    return PlasmicInside__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicInside";
  } else {
    func.displayName = `PlasmicInside.${nodeName}`;
  }
  return func;
}

export const PlasmicInside = Object.assign(
  // Top-level PlasmicInside renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    link: makeNodeComponent("link"),
    _: makeNodeComponent("_"),
    ul: makeNodeComponent("ul"),
    li: makeNodeComponent("li"),
    img: makeNodeComponent("img"),

    // Metadata about props expected for PlasmicInside
    internalVariantProps: PlasmicInside__VariantProps,
    internalArgProps: PlasmicInside__ArgProps
  }
);

export default PlasmicInside;
/* prettier-ignore-end */
